
CREATE TABLE users
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- CREATE TABLE posts
-- (
--     id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     title   VARCHAR(255) NOT NULL,
--     content TEXT,
--     author  VARCHAR(255),
--     user_id BIGINT,
--     CONSTRAINT fk_posts_users FOREIGN KEY (user_id) REFERENCES users(id)
-- );
--
--
-- INSERT INTO users (name) VALUES ('Alice');
-- INSERT INTO users (name) VALUES ('Bob');
-- INSERT INTO users (name) VALUES ('Charlie');
-- INSERT INTO users (name) VALUES ('David');
-- INSERT INTO users (name) VALUES ('Eva');
--
--
-- INSERT INTO posts (title, content, author, user_id) VALUES ('Post 1', 'Content for Post 1', 'Alice', 1);
-- INSERT INTO posts (title, content, author, user_id) VALUES ('Post 2', 'Content for Post 2', 'Alice', 1);
-- INSERT INTO posts (title, content, author, user_id) VALUES ('Post 3', 'Content for Post 3', 'Bob', 2);
--
